# å¼?å‘æ­¥éª?  å¯¼å…¥é…ç½®, ç¼–å†™ä¾èµ–
server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
    # è¿æ¥è¿œç¨‹ä»“åº“
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/codingce/springcloud-config.git  # æ˜¯httpsçš?, ä¸æ˜¯git

# é€šè¿‡config-server å¯ä»¥è¿æ¥åˆ°git è®¿é—®å…¶ä¸­çš„èµ„æºä»¥åŠé…ç½?  http://localhost:3344/application-dev.yml   http://localhost:3344/application/dev/master
# config-serveræœåŠ¡ç«?        giteeåœ°å€ï¼šhttps://gitee.com/codingce/springcloud-config.git