server:
  port: 9527
spring:
  application:
    name: springcloud-zuul


eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/, http://eureka7001.com:7001/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true

# info é…ç½®
info:
  app.name: codingce-springcloud
  cpmany.name: i.codingce.com.cn
  author: xzMhehe

# è·¯ç”±ç½‘å…³é…ç½®  æˆ‘ä»¬éœ?è¦è®¾ç½®åŸè·¯å¾„ä¸èƒ½è®¿é—®, ä»…å¯ä½¿ç”¨Zuulè·¯ç”±ç½‘å…³é…ç½®çš?  è·¯å¾„    (å·²åœ¨ win10 hosts  é‡Œé¢é…ç½® 127.0.0.1	www.codingce.com)
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept # ä¸èƒ½åœ¨ä½¿ç”¨è¿™ä¸ªè·¯å¾„è®¿é—®äº†  ignored-services: "*" éšè—å…¨éƒ¨çš„çœŸå®çš„é¡¹ç›®
  prefix: /mxz  # è®¾ç½®å…¬å…±çš„å‰ç¼?       å¯æœ‰å¯æ—   å? http://www.codingce.com:9527/mydept/dept/list    åŠ äº†ä¹‹å http://www.codingce.com:9527/mxz/mydept/dept/list

